version: "2.0"

services:
  # laravel       
  laravel:
    build:
      context: ./
      dockerfile: laravel.dockerfile
    image: laravel
    user: "1000:1000"
    container_name: laravel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - library-3

  # vue
  vue:
    stdin_open: true
    container_name: vue
    restart: always
    build:
      context: ../vue
      dockerfile: vue.dockerfile
    volumes:
      - /app/node_modules
      - ../vue:/app:cached
    networks:
      - library-3
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "80"
    ports:
      - "8080:8080"

  #Nginx Service
  webserver:
    depends_on:
      - laravel
      - vue
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - library-3

  # phpmyadmin
  admin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - library-3

  #Mysql DB
  mysql:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ../mysql:/mysql
    networks:
      - library-3

networks:
  library-3:
    driver: bridge
